CREATE TABLE "users" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "username" varchar,
  "email" varchar UNIQUE,
  "password" varchar,
  "birthdate" timestamp,
  "sex" varchar
);

CREATE TABLE "interests" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar UNIQUE,
  "description" text
);

CREATE TABLE "user_interests" (
  "user_id" int,
  "interest_id" int,
  "ignore" bool
);

CREATE TABLE "communities" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "name" varchar,
  "description" text,
  "created_at" timestamp
);

CREATE TABLE "community_members" (
  "user_id" int,
  "community_id" int,
  "role" varchar,
  "joined_at" timestamp
);

CREATE TABLE "posts" (
  "id" INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  "community_id" int,
  "user_id" int,
  "title" varchar,
  "content" text,
  "created_at" timestamp,
  "updated_at" timestamp
);

CREATE UNIQUE INDEX ON "user_interests" ("user_id", "interest_id");

CREATE UNIQUE INDEX ON "community_members" ("user_id", "community_id");

ALTER TABLE "user_interests" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "user_interests" ADD FOREIGN KEY ("interest_id") REFERENCES "interests" ("id");

ALTER TABLE "community_members" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");

ALTER TABLE "community_members" ADD FOREIGN KEY ("community_id") REFERENCES "communities" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("community_id") REFERENCES "communities" ("id");

ALTER TABLE "posts" ADD FOREIGN KEY ("user_id") REFERENCES "users" ("id");
